//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 01:34:50 PM CDT 
//


package mx.gob.se.rug.masiva.resultado.to;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tramites }
     * 
     */
    public Tramites createTramites() {
        return new Tramites();
    }

    /**
     * Create an instance of {@link Otorgante }
     * 
     */
    public Otorgante createOtorgante() {
        return new Otorgante();
    }

    /**
     * Create an instance of {@link Resumen }
     * 
     */
    public Resumen createResumen() {
        return new Resumen();
    }

    /**
     * Create an instance of {@link TramiteRes }
     * 
     */
    public TramiteRes createTramite() {
        return new TramiteRes();
    }

    /**
     * Create an instance of {@link ResultadoCargaMasiva }
     * 
     */
    public ResultadoCargaMasiva createResultadoCargaMasiva() {
        return new ResultadoCargaMasiva();
    }

}
