//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 01:34:50 PM CDT 
//


package mx.gob.se.rug.masiva.resultado.to;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="correctos" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="erroneos" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="mensaje-error" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="numero-registros" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "resumen")
public class Resumen {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String correctos;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String erroneos;
    @XmlAttribute(name = "mensaje-error", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String mensajeError;
    @XmlAttribute(name = "numero-registros", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String numeroRegistros;

    /**
     * Gets the value of the correctos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectos() {
        return correctos;
    }

    /**
     * Sets the value of the correctos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectos(String value) {
        this.correctos = value;
    }

    /**
     * Gets the value of the erroneos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErroneos() {
        return erroneos;
    }

    /**
     * Sets the value of the erroneos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErroneos(String value) {
        this.erroneos = value;
    }

    /**
     * Gets the value of the mensajeError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensajeError() {
        return mensajeError;
    }

    /**
     * Sets the value of the mensajeError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensajeError(String value) {
        this.mensajeError = value;
    }

    /**
     * Gets the value of the numeroRegistros property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegistros() {
        return numeroRegistros;
    }

    /**
     * Sets the value of the numeroRegistros property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegistros(String value) {
        this.numeroRegistros = value;
    }

}
