//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 01:34:50 PM CDT 
//


package mx.gob.se.rug.masiva.resultado.to;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}resumen"/>
 *         &lt;element ref="{}tramites"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resumen",
    "tramites"
})
@XmlRootElement(name = "resultado-carga-masiva")
public class ResultadoCargaMasiva {

    @XmlElement(required = true)
    protected Resumen resumen;
    @XmlElement(required = true)
    protected Tramites tramites;

    /**
     * Gets the value of the resumen property.
     * 
     * @return
     *     possible object is
     *     {@link Resumen }
     *     
     */
    public Resumen getResumen() {
        return resumen;
    }

    /**
     * Sets the value of the resumen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resumen }
     *     
     */
    public void setResumen(Resumen value) {
        this.resumen = value;
    }

    /**
     * Gets the value of the tramites property.
     * 
     * @return
     *     possible object is
     *     {@link Tramites }
     *     
     */
    public Tramites getTramites() {
        return tramites;
    }

    /**
     * Sets the value of the tramites property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramites }
     *     
     */
    public void setTramites(Tramites value) {
        this.tramites = value;
    }

}
