//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}persona-solicita-autoridad-instruye-asiento"/>
 *         &lt;element ref="{carga-masiva}vigencia"/>
 *         &lt;element ref="{carga-masiva}datos-anotacion"/>
 *         &lt;element ref="{carga-masiva}identificador-garantia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personaSolicitaAutoridadInstruyeAsiento",
    "vigencia",
    "datosAnotacion",
    "identificadorGarantia"
})
@XmlRootElement(name = "anotacion-garantia")
public class AnotacionGarantia {

    @XmlElement(name = "persona-solicita-autoridad-instruye-asiento", required = true)
    protected PersonaSolicitaAutoridadInstruyeAsiento personaSolicitaAutoridadInstruyeAsiento;
    @XmlElement(required = true)
    protected Vigencia vigencia;
    @XmlElement(name = "datos-anotacion", required = true)
    protected DatosAnotacion datosAnotacion;
    @XmlElement(name = "identificador-garantia", required = true)
    protected IdentificadorGarantia identificadorGarantia;

    /**
     * Gets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public PersonaSolicitaAutoridadInstruyeAsiento getPersonaSolicitaAutoridadInstruyeAsiento() {
        return personaSolicitaAutoridadInstruyeAsiento;
    }

    /**
     * Sets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public void setPersonaSolicitaAutoridadInstruyeAsiento(PersonaSolicitaAutoridadInstruyeAsiento value) {
        this.personaSolicitaAutoridadInstruyeAsiento = value;
    }

    /**
     * Gets the value of the vigencia property.
     * 
     * @return
     *     possible object is
     *     {@link Vigencia }
     *     
     */
    public Vigencia getVigencia() {
        return vigencia;
    }

    /**
     * Sets the value of the vigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vigencia }
     *     
     */
    public void setVigencia(Vigencia value) {
        this.vigencia = value;
    }

    /**
     * Gets the value of the datosAnotacion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosAnotacion }
     *     
     */
    public DatosAnotacion getDatosAnotacion() {
        return datosAnotacion;
    }

    /**
     * Sets the value of the datosAnotacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosAnotacion }
     *     
     */
    public void setDatosAnotacion(DatosAnotacion value) {
        this.datosAnotacion = value;
    }

    /**
     * Gets the value of the identificadorGarantia property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificadorGarantia }
     *     
     */
    public IdentificadorGarantia getIdentificadorGarantia() {
        return identificadorGarantia;
    }

    /**
     * Sets the value of the identificadorGarantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificadorGarantia }
     *     
     */
    public void setIdentificadorGarantia(IdentificadorGarantia value) {
        this.identificadorGarantia = value;
    }

}
