//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import mx.gob.se.rug.masiva.to.BienesEspeciales;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{carga-masiva}tipo-bien-mueble"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id-tipo-garantia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fecha-celebracion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="monto-maximo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id-moneda" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="descripcion-bienes-muebles" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="terminos-condiciones" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datos-instrumento-publico" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="b-datos-modificables" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoBienMueble",
    "bienesEspeciales"
})
//@XmlRootElement(name = "creacion")
public class Creacion {

    @XmlElement(name = "tipo-bien-mueble", required = true)
    protected List<TipoBienMueble> tipoBienMueble;
    @XmlAttribute(name = "id-tipo-garantia", required = true)
    protected String idTipoGarantia;
    @XmlAttribute(name = "fecha-registro", required = true)
    protected String fechaCelebracion;
    @XmlAttribute(name = "monto-maximo")
    protected String montoMaximo;
    @XmlAttribute(name = "id-moneda")
    protected String idMoneda;
    @XmlAttribute(name = "descripcion-bienes-muebles")
    protected String descripcionBienesMuebles;
    @XmlAttribute(name = "observaciones-adicionales")
    protected String terminosCondiciones;
    @XmlAttribute(name = "info-general-contrato")
    protected String datosInstrumentoPublico;    
    @XmlAttribute(name = "info-registro")
    protected String infoRegistro;
    @XmlAttribute(name = "b-atribuibles-no-afectos", required = true)
    protected String bDatosModificables;
    @XmlAttribute(name = "b-no-bienes-otorgados", required = true)
    protected String bNoBienesOtorgados;
    @XmlAttribute(name = "b-es-prioritaria", required = true)
    protected String bEsPrioritaria;
    @XmlAttribute(name = "b-en-otro-registro", required = true)
    protected String bEnOtroRegistro;    
    @XmlElement(name = "bienesEspeciales", required = true)
    protected BienesEspeciales bienesEspeciales;

    /**
     * Gets the value of the tipoBienMueble property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipoBienMueble property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoBienMueble().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoBienMueble }
     * 
     * 
     */
    public List<TipoBienMueble> getTipoBienMueble() {
        if (tipoBienMueble == null) {
            tipoBienMueble = new ArrayList<TipoBienMueble>();
        }
        return this.tipoBienMueble;
    }

    /**
     * Gets the value of the idTipoGarantia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTipoGarantia() {
        return idTipoGarantia;
    }

    /**
     * Sets the value of the idTipoGarantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTipoGarantia(String value) {
        this.idTipoGarantia = value;
    }

    /**
     * Gets the value of the fechaCelebracion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaCelebracion() {
        return fechaCelebracion;
    }

    /**
     * Sets the value of the fechaCelebracion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaCelebracion(String value) {
        this.fechaCelebracion = value;
    }

    /**
     * Gets the value of the montoMaximo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMontoMaximo() {
        return montoMaximo;
    }

    /**
     * Sets the value of the montoMaximo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMontoMaximo(String value) {
        this.montoMaximo = value;
    }

    /**
     * Gets the value of the idMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdMoneda() {
        return idMoneda;
    }

    /**
     * Sets the value of the idMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdMoneda(String value) {
        this.idMoneda = value;
    }

    /**
     * Gets the value of the descripcionBienesMuebles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionBienesMuebles() {
        return descripcionBienesMuebles;
    }

    /**
     * Sets the value of the descripcionBienesMuebles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionBienesMuebles(String value) {
        this.descripcionBienesMuebles = value;
    }

    /**
     * Gets the value of the terminosCondiciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminosCondiciones() {
        return terminosCondiciones;
    }

    /**
     * Sets the value of the terminosCondiciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminosCondiciones(String value) {
        this.terminosCondiciones = value;
    }

    /**
     * Gets the value of the datosInstrumentoPublico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatosInstrumentoPublico() {
        return datosInstrumentoPublico;
    }

    /**
     * Sets the value of the datosInstrumentoPublico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatosInstrumentoPublico(String value) {
        this.datosInstrumentoPublico = value;
    }

    /**
     * Gets the value of the bDatosModificables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBDatosModificables() {
        return bDatosModificables;
    }

    /**
     * Sets the value of the bDatosModificables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBDatosModificables(String value) {
        this.bDatosModificables = value;
    }

	public String getInfoRegistro() {
		return infoRegistro;
	}

	public void setInfoRegistro(String infoRegistro) {
		this.infoRegistro = infoRegistro;
	}

	public String getbNoBienesOtorgados() {
		return bNoBienesOtorgados;
	}

	public void setbNoBienesOtorgados(String bNoBienesOtorgados) {
		this.bNoBienesOtorgados = bNoBienesOtorgados;
	}

	public String getbEsPrioritaria() {
		return bEsPrioritaria;
	}

	public void setbEsPrioritaria(String bEsPrioritaria) {
		this.bEsPrioritaria = bEsPrioritaria;
	}

	public String getbEnOtroRegistro() {
		return bEnOtroRegistro;
	}

	public void setbEnOtroRegistro(String bEnOtroRegistro) {
		this.bEnOtroRegistro = bEnOtroRegistro;
	}

	public BienesEspeciales getBienesEspeciales() {
		 if (bienesEspeciales == null) {
			 bienesEspeciales = new BienesEspeciales();
	        }
		return bienesEspeciales;
	}

	public void setBienesEspeciales(BienesEspeciales bienesEspeciales) {
		this.bienesEspeciales = bienesEspeciales;
	}

}
