//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import mx.gob.se.rug.masiva.to.BienEspecial;
import mx.gob.se.rug.masiva.to.BienesEspeciales;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}creacion"/>
 *         &lt;element ref="{carga-masiva}obligacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {	
    "datosInstrumentoPublico",
    "terminos",
    "terminosCondiciones",
    "infoRegistro",
    "fechaCelebracion",
    "bDatosModificables",
    "bEsPrioritaria",
    "bNoBienesOtorgados",
    "bEnOtroRegistro",
    "descripcionBienesMuebles",
    "bienEspecial"    
})
@XmlRootElement(name = "garantia")
public class Garantia {

    @XmlElement(name = "fecha-registro", required = true)
    protected String fechaCelebracion;
    @XmlElement(name = "descripcion-bienes-muebles")
    protected String descripcionBienesMuebles;
    @XmlElement(name = "observaciones-adicionales")
    protected String terminosCondiciones;
    @XmlElement(name = "info-general-contrato")
    protected String datosInstrumentoPublico;    
    @XmlElement(name = "info-registro")
    protected String infoRegistro;
    @XmlElement(name = "b-atribuibles-no-afectos", required = true)
    protected String bDatosModificables;
    @XmlElement(name = "b-no-bienes-otorgados", required = true)
    protected String bNoBienesOtorgados;
    @XmlElement(name = "b-es-prioritaria", required = true)
    protected String bEsPrioritaria;
    @XmlElement(name = "b-en-otro-registro", required = true)
    protected String bEnOtroRegistro;    
    @XmlElement(name = "info-representante")
    protected String terminos;
    @XmlElement(name = "bien-especial", required = true)
    protected List<BienEspecial> bienEspecial;
	public String getFechaCelebracion() {
		return fechaCelebracion;
	}
	public void setFechaCelebracion(String fechaCelebracion) {
		this.fechaCelebracion = fechaCelebracion;
	}
	public String getDescripcionBienesMuebles() {
		return descripcionBienesMuebles;
	}
	public void setDescripcionBienesMuebles(String descripcionBienesMuebles) {
		this.descripcionBienesMuebles = descripcionBienesMuebles;
	}
	public String getTerminosCondiciones() {
		return terminosCondiciones;
	}
	public void setTerminosCondiciones(String terminosCondiciones) {
		this.terminosCondiciones = terminosCondiciones;
	}
	public String getDatosInstrumentoPublico() {
		return datosInstrumentoPublico;
	}
	public void setDatosInstrumentoPublico(String datosInstrumentoPublico) {
		this.datosInstrumentoPublico = datosInstrumentoPublico;
	}
	public String getInfoRegistro() {
		return infoRegistro;
	}
	public void setInfoRegistro(String infoRegistro) {
		this.infoRegistro = infoRegistro;
	}
	public String getbDatosModificables() {
		return bDatosModificables;
	}
	public void setbDatosModificables(String bDatosModificables) {
		this.bDatosModificables = bDatosModificables;
	}
	public String getbNoBienesOtorgados() {
		return bNoBienesOtorgados;
	}
	public void setbNoBienesOtorgados(String bNoBienesOtorgados) {
		this.bNoBienesOtorgados = bNoBienesOtorgados;
	}
	public String getbEsPrioritaria() {
		return bEsPrioritaria;
	}
	public void setbEsPrioritaria(String bEsPrioritaria) {
		this.bEsPrioritaria = bEsPrioritaria;
	}
	public String getbEnOtroRegistro() {
		return bEnOtroRegistro;
	}
	public void setbEnOtroRegistro(String bEnOtroRegistro) {
		this.bEnOtroRegistro = bEnOtroRegistro;
	}
	public String getTerminos() {
		return terminos;
	}
	public void setTerminos(String terminos) {
		this.terminos = terminos;
	}
	public List<BienEspecial> getBienEspecial() {
		return bienEspecial;
	}
	public void setBienEspecial(List<BienEspecial> bienEspecial) {
		this.bienEspecial = bienEspecial;
	}

}
