//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}persona-solicita-autoridad-instruye-asiento" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}partes"/>
 *         &lt;element ref="{carga-masiva}garantia"/>
 *         &lt;element ref="{carga-masiva}vigencia"/>
 *         &lt;element ref="{carga-masiva}identificador"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personaSolicitaAutoridadInstruyeAsiento",
    "partes",
    "garantia",
    "vigencia",
    "identificador"
})
@XmlRootElement(name = "inscripcion")
public class Inscripcion {

    @XmlElement(name = "persona-solicita-autoridad-instruye-asiento")
    protected PersonaSolicitaAutoridadInstruyeAsiento personaSolicitaAutoridadInstruyeAsiento;
    @XmlElement(required = true)
    protected Partes partes;
    @XmlElement(required = true)
    protected Garantia garantia;
    @XmlElement(required = true)
    protected Integer vigencia;
    @XmlElement(required = true)
    protected String identificador;

    /**
     * Gets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public PersonaSolicitaAutoridadInstruyeAsiento getPersonaSolicitaAutoridadInstruyeAsiento() {
        return personaSolicitaAutoridadInstruyeAsiento;
    }

    /**
     * Sets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public void setPersonaSolicitaAutoridadInstruyeAsiento(PersonaSolicitaAutoridadInstruyeAsiento value) {
        this.personaSolicitaAutoridadInstruyeAsiento = value;
    }

    /**
     * Gets the value of the partes property.
     * 
     * @return
     *     possible object is
     *     {@link Partes }
     *     
     */
    public Partes getPartes() {
        return partes;
    }

    /**
     * Sets the value of the partes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Partes }
     *     
     */
    public void setPartes(Partes value) {
        this.partes = value;
    }

    /**
     * Gets the value of the garantia property.
     * 
     * @return
     *     possible object is
     *     {@link Garantia }
     *     
     */
    public Garantia getGarantia() {
        return garantia;
    }

    /**
     * Sets the value of the garantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Garantia }
     *     
     */
    public void setGarantia(Garantia value) {
        this.garantia = value;
    }

    /**
     * Gets the value of the vigencia property.
     * 
     * @return
     *     possible object is
     *     {@link Vigencia }
     *     
     */
    public Integer getVigencia() {
        return vigencia;
    }

    /**
     * Sets the value of the vigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vigencia }
     *     
     */
    public void setVigencia(Integer value) {
        this.vigencia = value;
    }

    /**
     * Gets the value of the identificador property.
     * 
     * @return
     *     possible object is
     *     {@link Identificador }
     *     
     */
    public String getIdentificador() {
        return identificador;
    }

    /**
     * Sets the value of the identificador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identificador }
     *     
     */
    public void setIdentificador(String value) {
        this.identificador = value;
    }

}
