//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}persona-solicita-autoridad-instruye-asiento" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}eliminar-partes-modificacion" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}deudor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}datos-modificacion" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}obligacion-garantiza-modificacion"/>
 *         &lt;element ref="{carga-masiva}convenio"/>
 *         &lt;element ref="{carga-masiva}identificador-garantia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personaSolicitaAutoridadInstruyeAsiento",
    "partes",
    "garantia",
    "razon",
    "identificador",
    "idGarantia"
})
@XmlRootElement(name = "modificacion")
public class Modificacion {

    @XmlElement(name = "persona-solicita-autoridad-instruye-asiento")
    protected PersonaSolicitaAutoridadInstruyeAsiento personaSolicitaAutoridadInstruyeAsiento;
    @XmlElement(required = true)
    protected Partes partes;
    @XmlElement(required = true)
    protected Garantia garantia;
    @XmlElement(name = "razon-modificacion")
    protected String razon;
    @XmlElement(required = true)
    protected String identificador;
    @XmlElement(name="id-garantia")
    protected String idGarantia;
    

    /**
     * Gets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public PersonaSolicitaAutoridadInstruyeAsiento getPersonaSolicitaAutoridadInstruyeAsiento() {
        return personaSolicitaAutoridadInstruyeAsiento;
    }

    /**
     * Sets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public void setPersonaSolicitaAutoridadInstruyeAsiento(PersonaSolicitaAutoridadInstruyeAsiento value) {
        this.personaSolicitaAutoridadInstruyeAsiento = value;
    }

	public Partes getPartes() {
		return partes;
	}

	public void setPartes(Partes partes) {
		this.partes = partes;
	}

	public Garantia getGarantia() {
		return garantia;
	}

	public void setGarantia(Garantia garantia) {
		this.garantia = garantia;
	}

	public String getRazon() {
		return razon;
	}

	public void setRazon(String razon) {
		this.razon = razon;
	}

	public String getIdentificador() {
		return identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public String getIdGarantia() {
		return idGarantia;
	}

	public void setIdGarantia(String idGarantia) {
		this.idGarantia = idGarantia;
	}
}
