//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "carga-masiva", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.gob.se.rug.masiva.to.string;
