//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:22:20 AM CDT 
//


package mx.gob.se.rug.masiva.to.string;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}persona-solicita-autoridad-instruye-asiento" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}acreedor" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}eliminar-partes-rectificacion" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}partes-rectificacion" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}datos-garantia" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}obligacion-garantiza" minOccurs="0"/>
 *         &lt;element ref="{carga-masiva}identificador-garantia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personaSolicitaAutoridadInstruyeAsiento",
    "acreedor",
    "eliminarPartesRectificacion",
    "partesRectificacion",
    "datosGarantia",
    "obligacionGarantiza",
    "identificadorGarantia"
})
@XmlRootElement(name = "rectificacion-por-error")
public class RectificacionPorError {

    @XmlElement(name = "persona-solicita-autoridad-instruye-asiento")
    protected PersonaSolicitaAutoridadInstruyeAsiento personaSolicitaAutoridadInstruyeAsiento;
    protected Acreedor acreedor;
    @XmlElement(name = "eliminar-partes-rectificacion")
    protected EliminarPartesRectificacion eliminarPartesRectificacion;
    @XmlElement(name = "partes-rectificacion")
    protected PartesRectificacion partesRectificacion;
    @XmlElement(name = "datos-garantia")
    protected DatosGarantia datosGarantia;
    @XmlElement(name = "obligacion-garantiza")
    protected ObligacionGarantiza obligacionGarantiza;
    @XmlElement(name = "identificador-garantia", required = true)
    protected IdentificadorGarantia identificadorGarantia;

    /**
     * Gets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public PersonaSolicitaAutoridadInstruyeAsiento getPersonaSolicitaAutoridadInstruyeAsiento() {
        return personaSolicitaAutoridadInstruyeAsiento;
    }

    /**
     * Sets the value of the personaSolicitaAutoridadInstruyeAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaSolicitaAutoridadInstruyeAsiento }
     *     
     */
    public void setPersonaSolicitaAutoridadInstruyeAsiento(PersonaSolicitaAutoridadInstruyeAsiento value) {
        this.personaSolicitaAutoridadInstruyeAsiento = value;
    }

    /**
     * Gets the value of the acreedor property.
     * 
     * @return
     *     possible object is
     *     {@link Acreedor }
     *     
     */
    public Acreedor getAcreedor() {
        return acreedor;
    }

    /**
     * Sets the value of the acreedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acreedor }
     *     
     */
    public void setAcreedor(Acreedor value) {
        this.acreedor = value;
    }

    /**
     * Gets the value of the eliminarPartesRectificacion property.
     * 
     * @return
     *     possible object is
     *     {@link EliminarPartesRectificacion }
     *     
     */
    public EliminarPartesRectificacion getEliminarPartesRectificacion() {
        return eliminarPartesRectificacion;
    }

    /**
     * Sets the value of the eliminarPartesRectificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link EliminarPartesRectificacion }
     *     
     */
    public void setEliminarPartesRectificacion(EliminarPartesRectificacion value) {
        this.eliminarPartesRectificacion = value;
    }

    /**
     * Gets the value of the partesRectificacion property.
     * 
     * @return
     *     possible object is
     *     {@link PartesRectificacion }
     *     
     */
    public PartesRectificacion getPartesRectificacion() {
        return partesRectificacion;
    }

    /**
     * Sets the value of the partesRectificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartesRectificacion }
     *     
     */
    public void setPartesRectificacion(PartesRectificacion value) {
        this.partesRectificacion = value;
    }

    /**
     * Gets the value of the datosGarantia property.
     * 
     * @return
     *     possible object is
     *     {@link DatosGarantia }
     *     
     */
    public DatosGarantia getDatosGarantia() {
        return datosGarantia;
    }

    /**
     * Sets the value of the datosGarantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosGarantia }
     *     
     */
    public void setDatosGarantia(DatosGarantia value) {
        this.datosGarantia = value;
    }

    /**
     * Gets the value of the obligacionGarantiza property.
     * 
     * @return
     *     possible object is
     *     {@link ObligacionGarantiza }
     *     
     */
    public ObligacionGarantiza getObligacionGarantiza() {
        return obligacionGarantiza;
    }

    /**
     * Sets the value of the obligacionGarantiza property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObligacionGarantiza }
     *     
     */
    public void setObligacionGarantiza(ObligacionGarantiza value) {
        this.obligacionGarantiza = value;
    }

    /**
     * Gets the value of the identificadorGarantia property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificadorGarantia }
     *     
     */
    public IdentificadorGarantia getIdentificadorGarantia() {
        return identificadorGarantia;
    }

    /**
     * Sets the value of the identificadorGarantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificadorGarantia }
     *     
     */
    public void setIdentificadorGarantia(IdentificadorGarantia value) {
        this.identificadorGarantia = value;
    }

}
