
package gt.gob.rgm.rug.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "pagoService", targetNamespace = "https://rug.rgm.gob.gt/services/rug-rgm-web-service", wsdlLocation = "file:/C:/angular/src/rug-parent/rgm-rug-ws/src/main/resources/wsdl/pagoService.wsdl")
public class PagoService
    extends Service
{

    private final static URL PAGOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gt.gob.rgm.rug.ws.PagoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gt.gob.rgm.rug.ws.PagoService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/angular/src/rug-parent/rgm-rug-ws/src/main/resources/wsdl/pagoService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/angular/src/rug-parent/rgm-rug-ws/src/main/resources/wsdl/pagoService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGOSERVICE_WSDL_LOCATION = url;
    }

    public PagoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoService() {
        super(PAGOSERVICE_WSDL_LOCATION, new QName("https://rug.rgm.gob.gt/services/rug-rgm-web-service", "pagoService"));
    }

    /**
     * 
     * @return
     *     returns PagoServicePortType
     */
    @WebEndpoint(name = "PagoEndpointPort")
    public PagoServicePortType getPagoEndpointPort() {
        return super.getPort(new QName("https://rug.rgm.gob.gt/services/rug-rgm-web-service", "PagoEndpointPort"), PagoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoServicePortType
     */
    @WebEndpoint(name = "PagoEndpointPort")
    public PagoServicePortType getPagoEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://rug.rgm.gob.gt/services/rug-rgm-web-service", "PagoEndpointPort"), PagoServicePortType.class, features);
    }

}
