//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 01:24:04 PM CDT 
//


package mx.gob.se.rug.masiva.to;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}inscripcion"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}cancelacion"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}modificacion"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}renovacion-reduccion"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}transmision"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}rectificacion-por-error"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}anotacion-garantia"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}anotacion"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{carga-masiva}aviso-preventivo"/>
 *         &lt;/sequence>
 *         &lt;element ref="{carga-masiva}acreedores"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inscripcion",
    "cancelacion",
    "modificacion",
    "renovacionReduccion",
    "transmision",
    "rectificacionPorError",
    "anotacionGarantia",
    "anotacion",
    "avisoPreventivo",
    "traslado",
    "acreedores"
})
@XmlRootElement(name = "carga-masiva")
public class CargaMasiva {

    protected List<Inscripcion> inscripcion;
    protected List<Cancelacion> cancelacion;
    protected List<Modificacion> modificacion;
    @XmlElement(name = "renovacion-reduccion")
    protected List<RenovacionReduccion> renovacionReduccion;
    protected List<Transmision> transmision;
    @XmlElement(name = "rectificacion-por-error")
    protected List<RectificacionPorError> rectificacionPorError;
    @XmlElement(name = "anotacion-garantia")
    protected List<AnotacionGarantia> anotacionGarantia;
    protected List<Anotacion> anotacion;
    @XmlElement(name = "aviso-preventivo")
    protected List<AvisoPreventivo> avisoPreventivo;
    protected Acreedores acreedores;
    @XmlElement(name = "traslado")
    protected List<Inscripcion> traslado;
    @XmlElement(name = "ejecucion")
    protected List<Ejecucion> ejecucion;

    /**
     * Gets the value of the inscripcion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inscripcion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInscripcion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inscripcion }
     * 
     * 
     */
    public List<Inscripcion> getInscripcion() {
        if (inscripcion == null) {
            inscripcion = new ArrayList<Inscripcion>();
        }
        return this.inscripcion;
    }

    /**
     * Gets the value of the cancelacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancelacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancelacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cancelacion }
     * 
     * 
     */
    public List<Cancelacion> getCancelacion() {
        if (cancelacion == null) {
            cancelacion = new ArrayList<Cancelacion>();
        }
        return this.cancelacion;
    }

    /**
     * Gets the value of the modificacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modificacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModificacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modificacion }
     * 
     * 
     */
    public List<Modificacion> getModificacion() {
        if (modificacion == null) {
            modificacion = new ArrayList<Modificacion>();
        }
        return this.modificacion;
    }

    /**
     * Gets the value of the renovacionReduccion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the renovacionReduccion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRenovacionReduccion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RenovacionReduccion }
     * 
     * 
     */
    public List<RenovacionReduccion> getRenovacionReduccion() {
        if (renovacionReduccion == null) {
            renovacionReduccion = new ArrayList<RenovacionReduccion>();
        }
        return this.renovacionReduccion;
    }

    /**
     * Gets the value of the transmision property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transmision property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransmision().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transmision }
     * 
     * 
     */
    public List<Transmision> getTransmision() {
        if (transmision == null) {
            transmision = new ArrayList<Transmision>();
        }
        return this.transmision;
    }

    /**
     * Gets the value of the rectificacionPorError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rectificacionPorError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRectificacionPorError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RectificacionPorError }
     * 
     * 
     */
    public List<RectificacionPorError> getRectificacionPorError() {
        if (rectificacionPorError == null) {
            rectificacionPorError = new ArrayList<RectificacionPorError>();
        }
        return this.rectificacionPorError;
    }

    /**
     * Gets the value of the anotacionGarantia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anotacionGarantia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnotacionGarantia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnotacionGarantia }
     * 
     * 
     */
    public List<AnotacionGarantia> getAnotacionGarantia() {
        if (anotacionGarantia == null) {
            anotacionGarantia = new ArrayList<AnotacionGarantia>();
        }
        return this.anotacionGarantia;
    }

    /**
     * Gets the value of the anotacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anotacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnotacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Anotacion }
     * 
     * 
     */
    public List<Anotacion> getAnotacion() {
        if (anotacion == null) {
            anotacion = new ArrayList<Anotacion>();
        }
        return this.anotacion;
    }

    /**
     * Gets the value of the avisoPreventivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avisoPreventivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvisoPreventivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AvisoPreventivo }
     * 
     * 
     */
    public List<AvisoPreventivo> getAvisoPreventivo() {
        if (avisoPreventivo == null) {
            avisoPreventivo = new ArrayList<AvisoPreventivo>();
        }
        return this.avisoPreventivo;
    }

    /**
     * Gets the value of the acreedores property.
     * 
     * @return
     *     possible object is
     *     {@link Acreedores }
     *     
     */
    public Acreedores getAcreedores() {
        return acreedores;
    }

    /**
     * Sets the value of the acreedores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acreedores }
     *     
     */
    public void setAcreedores(Acreedores value) {
        this.acreedores = value;
    }

	public List<Inscripcion> getTraslado() {
		 if (traslado == null) {
			 traslado = new ArrayList<Inscripcion>();
	        }
		return this.traslado;
	}
	
	public List<Ejecucion> getEjecucion() {
		if(ejecucion == null) {
			ejecucion = new ArrayList<Ejecucion>();
		}
		return ejecucion;
	}

}
