//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 01:24:04 PM CDT 
//


package mx.gob.se.rug.masiva.to;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{carga-masiva}creacion"/>
 *         &lt;element ref="{carga-masiva}obligacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creacion",
    "obligacion"
})
@XmlRootElement(name = "garantia")
public class Garantia {

    @XmlElement(required = true)
    protected Creacion creacion;
    @XmlElement(required = true)
    protected Obligacion obligacion;

    /**
     * Gets the value of the creacion property.
     * 
     * @return
     *     possible object is
     *     {@link Creacion }
     *     
     */
    public Creacion getCreacion() {
        return creacion;
    }

    /**
     * Sets the value of the creacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Creacion }
     *     
     */
    public void setCreacion(Creacion value) {
        this.creacion = value;
    }

    /**
     * Gets the value of the obligacion property.
     * 
     * @return
     *     possible object is
     *     {@link Obligacion }
     *     
     */
    public Obligacion getObligacion() {
        return obligacion;
    }

    /**
     * Sets the value of the obligacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obligacion }
     *     
     */
    public void setObligacion(Obligacion value) {
        this.obligacion = value;
    }

}
