//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 01:24:04 PM CDT 
//


package mx.gob.se.rug.masiva.to;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.se.rug.masiva.to package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.se.rug.masiva.to
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatosModificacion }
     * 
     */
    public DatosModificacion createDatosModificacion() {
        return new DatosModificacion();
    }

    /**
     * Create an instance of {@link Obligacion }
     * 
     */
    public Obligacion createObligacion() {
        return new Obligacion();
    }

    /**
     * Create an instance of {@link DatosGarantia }
     * 
     */
    public DatosGarantia createDatosGarantia() {
        return new DatosGarantia();
    }

    /**
     * Create an instance of {@link Cancelacion }
     * 
     */
    public Cancelacion createCancelacion() {
        return new Cancelacion();
    }

    /**
     * Create an instance of {@link Acreedor }
     * 
     */
    public Acreedor createAcreedor() {
        return new Acreedor();
    }

    /**
     * Create an instance of {@link EliminarPartesTransmision }
     * 
     */
    public EliminarPartesTransmision createEliminarPartesTransmision() {
        return new EliminarPartesTransmision();
    }

    /**
     * Create an instance of {@link AcreedorAutoridad }
     * 
     */
    public AcreedorAutoridad createAcreedorAutoridad() {
        return new AcreedorAutoridad();
    }

    /**
     * Create an instance of {@link DatosRenovacionReduccion }
     * 
     */
    public DatosRenovacionReduccion createDatosRenovacionReduccion() {
        return new DatosRenovacionReduccion();
    }

    /**
     * Create an instance of {@link ObligacionGarantiza }
     * 
     */
    public ObligacionGarantiza createObligacionGarantiza() {
        return new ObligacionGarantiza();
    }

    /**
     * Create an instance of {@link Anotacion }
     * 
     */
    public Anotacion createAnotacion() {
        return new Anotacion();
    }

    /**
     * Create an instance of {@link Convenio }
     * 
     */
    public Convenio createConvenio() {
        return new Convenio();
    }

    /**
     * Create an instance of {@link AcreedorAdicional }
     * 
     */
    public AcreedorAdicional createAcreedorAdicional() {
        return new AcreedorAdicional();
    }

    /**
     * Create an instance of {@link PartesRectificacion }
     * 
     */
    public PartesRectificacion createPartesRectificacion() {
        return new PartesRectificacion();
    }

    /**
     * Create an instance of {@link RectificacionPorError }
     * 
     */
    public RectificacionPorError createRectificacionPorError() {
        return new RectificacionPorError();
    }

    /**
     * Create an instance of {@link DatosAvisoPreventivo }
     * 
     */
    public DatosAvisoPreventivo createDatosAvisoPreventivo() {
        return new DatosAvisoPreventivo();
    }

    /**
     * Create an instance of {@link RenovacionReduccion }
     * 
     */
    public RenovacionReduccion createRenovacionReduccion() {
        return new RenovacionReduccion();
    }

    /**
     * Create an instance of {@link ObligacionGarantizaModificacion }
     * 
     */
    public ObligacionGarantizaModificacion createObligacionGarantizaModificacion() {
        return new ObligacionGarantizaModificacion();
    }

    /**
     * Create an instance of {@link DatosTransmision }
     * 
     */
    public DatosTransmision createDatosTransmision() {
        return new DatosTransmision();
    }

    /**
     * Create an instance of {@link DatosAnotacion }
     * 
     */
    public DatosAnotacion createDatosAnotacion() {
        return new DatosAnotacion();
    }

    /**
     * Create an instance of {@link EliminarPartesModificacion }
     * 
     */
    public EliminarPartesModificacion createEliminarPartesModificacion() {
        return new EliminarPartesModificacion();
    }

    /**
     * Create an instance of {@link TipoBienMueble }
     * 
     */
    public TipoBienMueble createTipoBienMueble() {
        return new TipoBienMueble();
    }

    /**
     * Create an instance of {@link AnotacionGarantia }
     * 
     */
    public AnotacionGarantia createAnotacionGarantia() {
        return new AnotacionGarantia();
    }

    /**
     * Create an instance of {@link Creacion }
     * 
     */
    public Creacion createCreacion() {
        return new Creacion();
    }

    /**
     * Create an instance of {@link Modificacion }
     * 
     */
    public Modificacion createModificacion() {
        return new Modificacion();
    }

    /**
     * Create an instance of {@link Deudor }
     * 
     */
    public Deudor createDeudor() {
        return new Deudor();
    }

    /**
     * Create an instance of {@link Acreedores }
     * 
     */
    public Acreedores createAcreedores() {
        return new Acreedores();
    }

    /**
     * Create an instance of {@link Partes }
     * 
     */
    public Partes createPartes() {
        return new Partes();
    }

    /**
     * Create an instance of {@link PersonaSolicitaAutoridadInstruyeAsiento }
     * 
     */
    public PersonaSolicitaAutoridadInstruyeAsiento createPersonaSolicitaAutoridadInstruyeAsiento() {
        return new PersonaSolicitaAutoridadInstruyeAsiento();
    }

    /**
     * Create an instance of {@link IdentificadorGarantia }
     * 
     */
    public IdentificadorGarantia createIdentificadorGarantia() {
        return new IdentificadorGarantia();
    }

    /**
     * Create an instance of {@link Transmision }
     * 
     */
    public Transmision createTransmision() {
        return new Transmision();
    }

    /**
     * Create an instance of {@link Garantia }
     * 
     */
    public Garantia createGarantia() {
        return new Garantia();
    }

    /**
     * Create an instance of {@link Vigencia }
     * 
     */
    public Vigencia createVigencia() {
        return new Vigencia();
    }

    /**
     * Create an instance of {@link Inscripcion }
     * 
     */
    public Inscripcion createInscripcion() {
        return new Inscripcion();
    }

    /**
     * Create an instance of {@link EliminarPartesRectificacion }
     * 
     */
    public EliminarPartesRectificacion createEliminarPartesRectificacion() {
        return new EliminarPartesRectificacion();
    }

    /**
     * Create an instance of {@link Otorgante }
     * 
     */
    public Otorgante createOtorgante() {
        return new Otorgante();
    }

    /**
     * Create an instance of {@link AvisoPreventivo }
     * 
     */
    public AvisoPreventivo createAvisoPreventivo() {
        return new AvisoPreventivo();
    }

    /**
     * Create an instance of {@link CargaMasiva }
     * 
     */
    public CargaMasiva createCargaMasiva() {
        return new CargaMasiva();
    }

    /**
     * Create an instance of {@link Identificador }
     * 
     */
    public Identificador createIdentificador() {
        return new Identificador();
    }

}
