//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 09:00:07 PM CDT 
//


package mx.gob.se.rug.firma.cadenaoriginal.anotacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usuario-captura">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id-usuario" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="usuario-firma">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id-usuario" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tramite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id-tramite-padre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="id-tramite-nuevo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="id-tipo-tramite" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informacion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="persona-autoridad-autoriza" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="anotacion" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="origen" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="vigencia" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="otorgante">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fisico">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="moral">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="denominacion-social" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usuarioCaptura",
    "usuarioFirma",
    "tramite",
    "informacion",
    "otorgante"
})
@XmlRootElement(name = "anotacion")
public class Anotacion {

    @XmlElement(name = "usuario-captura", required = true)
    protected Anotacion.UsuarioCaptura usuarioCaptura;
    @XmlElement(name = "usuario-firma", required = true)
    protected Anotacion.UsuarioFirma usuarioFirma;
    @XmlElement(required = true)
    protected Anotacion.Tramite tramite;
    @XmlElement(required = true)
    protected Anotacion.Informacion informacion;
    @XmlElement(required = true)
    protected Anotacion.Otorgante otorgante;

    /**
     * Gets the value of the usuarioCaptura property.
     * 
     * @return
     *     possible object is
     *     {@link Anotacion.UsuarioCaptura }
     *     
     */
    public Anotacion.UsuarioCaptura getUsuarioCaptura() {
        return usuarioCaptura;
    }

    /**
     * Sets the value of the usuarioCaptura property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anotacion.UsuarioCaptura }
     *     
     */
    public void setUsuarioCaptura(Anotacion.UsuarioCaptura value) {
        this.usuarioCaptura = value;
    }

    /**
     * Gets the value of the usuarioFirma property.
     * 
     * @return
     *     possible object is
     *     {@link Anotacion.UsuarioFirma }
     *     
     */
    public Anotacion.UsuarioFirma getUsuarioFirma() {
        return usuarioFirma;
    }

    /**
     * Sets the value of the usuarioFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anotacion.UsuarioFirma }
     *     
     */
    public void setUsuarioFirma(Anotacion.UsuarioFirma value) {
        this.usuarioFirma = value;
    }

    /**
     * Gets the value of the tramite property.
     * 
     * @return
     *     possible object is
     *     {@link Anotacion.Tramite }
     *     
     */
    public Anotacion.Tramite getTramite() {
        return tramite;
    }

    /**
     * Sets the value of the tramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anotacion.Tramite }
     *     
     */
    public void setTramite(Anotacion.Tramite value) {
        this.tramite = value;
    }

    /**
     * Gets the value of the informacion property.
     * 
     * @return
     *     possible object is
     *     {@link Anotacion.Informacion }
     *     
     */
    public Anotacion.Informacion getInformacion() {
        return informacion;
    }

    /**
     * Sets the value of the informacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anotacion.Informacion }
     *     
     */
    public void setInformacion(Anotacion.Informacion value) {
        this.informacion = value;
    }

    /**
     * Gets the value of the otorgante property.
     * 
     * @return
     *     possible object is
     *     {@link Anotacion.Otorgante }
     *     
     */
    public Anotacion.Otorgante getOtorgante() {
        return otorgante;
    }

    /**
     * Sets the value of the otorgante property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anotacion.Otorgante }
     *     
     */
    public void setOtorgante(Anotacion.Otorgante value) {
        this.otorgante = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="persona-autoridad-autoriza" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="anotacion" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="origen" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="vigencia" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Informacion {

        @XmlAttribute(name = "persona-autoridad-autoriza")
        @XmlSchemaType(name = "anySimpleType")
        protected String personaAutoridadAutoriza;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String anotacion;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String origen;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String vigencia;

        /**
         * Gets the value of the personaAutoridadAutoriza property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonaAutoridadAutoriza() {
            return personaAutoridadAutoriza;
        }

        /**
         * Sets the value of the personaAutoridadAutoriza property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonaAutoridadAutoriza(String value) {
            this.personaAutoridadAutoriza = value;
        }

        /**
         * Gets the value of the anotacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnotacion() {
            return anotacion;
        }

        /**
         * Sets the value of the anotacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnotacion(String value) {
            this.anotacion = value;
        }

        /**
         * Gets the value of the origen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigen() {
            return origen;
        }

        /**
         * Sets the value of the origen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigen(String value) {
            this.origen = value;
        }

        /**
         * Gets the value of the vigencia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVigencia() {
            return vigencia;
        }

        /**
         * Sets the value of the vigencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVigencia(String value) {
            this.vigencia = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fisico">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="moral">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="denominacion-social" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fisico",
        "moral"
    })
    public static class Otorgante {

        @XmlElement(required = true)
        protected Anotacion.Otorgante.Fisico fisico;
        @XmlElement(required = true)
        protected Anotacion.Otorgante.Moral moral;

        /**
         * Gets the value of the fisico property.
         * 
         * @return
         *     possible object is
         *     {@link Anotacion.Otorgante.Fisico }
         *     
         */
        public Anotacion.Otorgante.Fisico getFisico() {
            return fisico;
        }

        /**
         * Sets the value of the fisico property.
         * 
         * @param value
         *     allowed object is
         *     {@link Anotacion.Otorgante.Fisico }
         *     
         */
        public void setFisico(Anotacion.Otorgante.Fisico value) {
            this.fisico = value;
        }

        /**
         * Gets the value of the moral property.
         * 
         * @return
         *     possible object is
         *     {@link Anotacion.Otorgante.Moral }
         *     
         */
        public Anotacion.Otorgante.Moral getMoral() {
            return moral;
        }

        /**
         * Sets the value of the moral property.
         * 
         * @param value
         *     allowed object is
         *     {@link Anotacion.Otorgante.Moral }
         *     
         */
        public void setMoral(Anotacion.Otorgante.Moral value) {
            this.moral = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Fisico {

            @XmlAttribute(name = "id-persona")
            @XmlSchemaType(name = "anySimpleType")
            protected String idPersona;
            @XmlAttribute
            @XmlSchemaType(name = "anySimpleType")
            protected String nombre;
            @XmlAttribute
            @XmlSchemaType(name = "anySimpleType")
            protected String apaterno;
            @XmlAttribute
            @XmlSchemaType(name = "anySimpleType")
            protected String amaterno;
            @XmlAttribute(name = "folio-electronico")
            @XmlSchemaType(name = "anySimpleType")
            protected String folioElectronico;

            /**
             * Gets the value of the idPersona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdPersona() {
                return idPersona;
            }

            /**
             * Sets the value of the idPersona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdPersona(String value) {
                this.idPersona = value;
            }

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the apaterno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApaterno() {
                return apaterno;
            }

            /**
             * Sets the value of the apaterno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApaterno(String value) {
                this.apaterno = value;
            }

            /**
             * Gets the value of the amaterno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAmaterno() {
                return amaterno;
            }

            /**
             * Sets the value of the amaterno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAmaterno(String value) {
                this.amaterno = value;
            }

            /**
             * Gets the value of the folioElectronico property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolioElectronico() {
                return folioElectronico;
            }

            /**
             * Sets the value of the folioElectronico property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolioElectronico(String value) {
                this.folioElectronico = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id-persona" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="denominacion-social" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="folio-electronico" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Moral {

            @XmlAttribute(name = "id-persona")
            @XmlSchemaType(name = "anySimpleType")
            protected String idPersona;
            @XmlAttribute(name = "denominacion-social")
            @XmlSchemaType(name = "anySimpleType")
            protected String denominacionSocial;
            @XmlAttribute(name = "folio-electronico")
            @XmlSchemaType(name = "anySimpleType")
            protected String folioElectronico;

            /**
             * Gets the value of the idPersona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdPersona() {
                return idPersona;
            }

            /**
             * Sets the value of the idPersona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdPersona(String value) {
                this.idPersona = value;
            }

            /**
             * Gets the value of the denominacionSocial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDenominacionSocial() {
                return denominacionSocial;
            }

            /**
             * Sets the value of the denominacionSocial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDenominacionSocial(String value) {
                this.denominacionSocial = value;
            }

            /**
             * Gets the value of the folioElectronico property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolioElectronico() {
                return folioElectronico;
            }

            /**
             * Sets the value of the folioElectronico property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolioElectronico(String value) {
                this.folioElectronico = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id-tramite-padre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="id-tramite-nuevo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="id-tipo-tramite" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Tramite {

        @XmlAttribute(name = "id-tramite-padre")
        @XmlSchemaType(name = "anySimpleType")
        protected String idTramitePadre;
        @XmlAttribute(name = "id-tramite-nuevo")
        @XmlSchemaType(name = "anySimpleType")
        protected String idTramiteNuevo;
        @XmlAttribute(name = "id-tipo-tramite")
        @XmlSchemaType(name = "anySimpleType")
        protected String idTipoTramite;

        /**
         * Gets the value of the idTramitePadre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdTramitePadre() {
            return idTramitePadre;
        }

        /**
         * Sets the value of the idTramitePadre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdTramitePadre(String value) {
            this.idTramitePadre = value;
        }

        /**
         * Gets the value of the idTramiteNuevo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdTramiteNuevo() {
            return idTramiteNuevo;
        }

        /**
         * Sets the value of the idTramiteNuevo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdTramiteNuevo(String value) {
            this.idTramiteNuevo = value;
        }

        /**
         * Gets the value of the idTipoTramite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdTipoTramite() {
            return idTipoTramite;
        }

        /**
         * Sets the value of the idTipoTramite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdTipoTramite(String value) {
            this.idTipoTramite = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id-usuario" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsuarioCaptura {

        @XmlAttribute(name = "id-usuario")
        @XmlSchemaType(name = "anySimpleType")
        protected String idUsuario;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String nombre;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String apaterno;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String amaterno;

        /**
         * Gets the value of the idUsuario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdUsuario() {
            return idUsuario;
        }

        /**
         * Sets the value of the idUsuario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdUsuario(String value) {
            this.idUsuario = value;
        }

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the apaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApaterno() {
            return apaterno;
        }

        /**
         * Sets the value of the apaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApaterno(String value) {
            this.apaterno = value;
        }

        /**
         * Gets the value of the amaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmaterno() {
            return amaterno;
        }

        /**
         * Sets the value of the amaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmaterno(String value) {
            this.amaterno = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id-usuario" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="apaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="amaterno" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsuarioFirma {

        @XmlAttribute(name = "id-usuario")
        @XmlSchemaType(name = "anySimpleType")
        protected String idUsuario;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String nombre;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String apaterno;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String amaterno;

        /**
         * Gets the value of the idUsuario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdUsuario() {
            return idUsuario;
        }

        /**
         * Sets the value of the idUsuario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdUsuario(String value) {
            this.idUsuario = value;
        }

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the apaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApaterno() {
            return apaterno;
        }

        /**
         * Sets the value of the apaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApaterno(String value) {
            this.apaterno = value;
        }

        /**
         * Gets the value of the amaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmaterno() {
            return amaterno;
        }

        /**
         * Sets the value of the amaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmaterno(String value) {
            this.amaterno = value;
        }

    }

}
