//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 09:00:07 PM CDT 
//


package mx.gob.se.rug.firma.cadenaoriginal.anotacion;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.se.rug.firmaelectronica.cadenaoriginal.anotacion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.se.rug.firmaelectronica.cadenaoriginal.anotacion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Anotacion.Tramite }
     * 
     */
    public Anotacion.Tramite createAnotacionTramite() {
        return new Anotacion.Tramite();
    }

    /**
     * Create an instance of {@link Anotacion.UsuarioCaptura }
     * 
     */
    public Anotacion.UsuarioCaptura createAnotacionUsuarioCaptura() {
        return new Anotacion.UsuarioCaptura();
    }

    /**
     * Create an instance of {@link Anotacion.Otorgante.Fisico }
     * 
     */
    public Anotacion.Otorgante.Fisico createAnotacionOtorganteFisico() {
        return new Anotacion.Otorgante.Fisico();
    }

    /**
     * Create an instance of {@link Anotacion }
     * 
     */
    public Anotacion createAnotacion() {
        return new Anotacion();
    }

    /**
     * Create an instance of {@link Anotacion.Otorgante.Moral }
     * 
     */
    public Anotacion.Otorgante.Moral createAnotacionOtorganteMoral() {
        return new Anotacion.Otorgante.Moral();
    }

    /**
     * Create an instance of {@link Anotacion.Informacion }
     * 
     */
    public Anotacion.Informacion createAnotacionInformacion() {
        return new Anotacion.Informacion();
    }

    /**
     * Create an instance of {@link Anotacion.UsuarioFirma }
     * 
     */
    public Anotacion.UsuarioFirma createAnotacionUsuarioFirma() {
        return new Anotacion.UsuarioFirma();
    }

    /**
     * Create an instance of {@link Anotacion.Otorgante }
     * 
     */
    public Anotacion.Otorgante createAnotacionOtorgante() {
        return new Anotacion.Otorgante();
    }

}
