//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 12:56:13 PM CDT 
//


package mx.gob.se.rug.boleta.to;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}otorgante" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cadena-unica-datos" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="clave-rastreo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fecha-asiento" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id-garantia" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="vigencia" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otorgante"
})
@XmlRootElement(name = "tramite")
public class Tramite {

    @XmlElement(required = true)
    protected List<Otorgante> otorgante;
    @XmlAttribute(name = "cadena-unica-datos", required = true)
    protected BigInteger cadenaUnicaDatos;
    @XmlAttribute(name = "clave-rastreo", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String claveRastreo;
    @XmlAttribute(name = "fecha-asiento", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fechaAsiento;
    @XmlAttribute(name = "id-garantia", required = true)
    protected BigInteger idGarantia;
    @XmlAttribute(required = true)
    protected BigInteger vigencia;

    /**
     * Gets the value of the otorgante property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otorgante property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtorgante().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Otorgante }
     * 
     * 
     */
    public List<Otorgante> getOtorgante() {
        if (otorgante == null) {
            otorgante = new ArrayList<Otorgante>();
        }
        return this.otorgante;
    }

    /**
     * Gets the value of the cadenaUnicaDatos property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCadenaUnicaDatos() {
        return cadenaUnicaDatos;
    }

    /**
     * Sets the value of the cadenaUnicaDatos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCadenaUnicaDatos(BigInteger value) {
        this.cadenaUnicaDatos = value;
    }

    /**
     * Gets the value of the claveRastreo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveRastreo() {
        return claveRastreo;
    }

    /**
     * Sets the value of the claveRastreo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveRastreo(String value) {
        this.claveRastreo = value;
    }

    /**
     * Gets the value of the fechaAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaAsiento() {
        return fechaAsiento;
    }

    /**
     * Sets the value of the fechaAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaAsiento(String value) {
        this.fechaAsiento = value;
    }

    /**
     * Gets the value of the idGarantia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdGarantia() {
        return idGarantia;
    }

    /**
     * Sets the value of the idGarantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdGarantia(BigInteger value) {
        this.idGarantia = value;
    }

    /**
     * Gets the value of the vigencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVigencia() {
        return vigencia;
    }

    /**
     * Sets the value of the vigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVigencia(BigInteger value) {
        this.vigencia = value;
    }

}
